---
title: "belimov Al"
author: "GrGladkov"
date: "06 03 2020"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Import phyloseq object
rds format

```{r, message=FALSE, echo=TRUE}
library(phyloseq)
library(tidyverse)
ps <- readRDS(file = "~/storage/al_R/rf/ps.f.dec.rds")
```

### nice rownames 
```{r}

```

###Alpha richess
1903 без In - неадекватная кривая разрежения
Удалить 
```{r, message=FALSE,echo=TRUE, fig.height=10, fig.width=14}
plot_rich_reads_samlenames_lm <- function(ps.f){
  rish <- estimate_richness(ps.f, measures = "Observed")
  reads.sum <- as.data.frame(sample_sums(ps.f))
  reads.summary <- cbind(rish, reads.sum)
  colnames(reads.summary) <- c("otus","reads")
  reads.summary["Description"] <- rownames(ps.f@sam_data)
  reads.summary["Repeats"] <- ps.f@sam_data$Description
  reads.summary["Plant"] <- ps.f@sam_data$Plant
  library(ggrepel)
  require(ggforce)
  p1 <- ggplot(data=reads.summary) + geom_point(aes(y=otus, x=log2(reads), color=Repeats),size=3) + geom_text_repel(aes(y=otus, x=log2(reads), label=Repeats)) + theme_bw()+
    geom_smooth(aes(y=otus, x=log2(reads), fill=Repeats, color=Repeats),method=lm, se=FALSE, ymin = 1) + scale_x_continuous(sec.axis = sec_axis(sec.axis ~ 2**.)) 
  # geom_mark_ellipse(aes(y = otus, x=reads, group = Repeats, label = Repeats, color = Repeats), label.fontsize = 10, label.buffer = unit(2, "mm"), label.minwidth = unit(5, "mm"),con.cap = unit(0.1, "mm"))
  
  return(p1)
}

plot_rich_reads_samlenames_lm(ps)
```
###Split
```{r}
ps.f.s1903 <- prune_samples(sample_data(ps.f.ch)$Plant %in% c("s1903"), ps.f.ch)
ps.f.s1903 <- prune_taxa(taxa_sums(ps.f.s1903) > 0,ps.f.s1903)

ps.f.s7307 <- prune_samples(sample_data(ps.f.ch)$Plant %in% c("s7307"), ps.f.ch)
ps.f.s7307 <- prune_taxa(taxa_sums(ps.f.s7307) > 0,ps.f.s7307)

ps.f.s8473 <- prune_samples(sample_data(ps.f.ch)$Plant %in% c("s8473"), ps.f.ch)
ps.f.s8473 <- prune_taxa(taxa_sums(ps.f.s8473) > 0,ps.f.s8473)

ps.f.s8353 <- prune_samples(sample_data(ps.f.ch)$Plant %in% c("s8353"), ps.f.ch)
ps.f.s8353 <- prune_taxa(taxa_sums(ps.f.s8353) > 0,ps.f.s8353)

physeq <- ps.f.s1903
physeq@sam_data$Al

physeq.Al.pos <- prune_samples(sample_data(physeq)$Al %in% c("pos"), physeq)
physeq.Al.pos <- prune_taxa(taxa_sums(physeq.Al.pos) > 0, physeq.Al.pos)

physeq.Al.neg <- prune_samples(sample_data(physeq)$Al %in% c("neg"),physeq)
physeq.Al.neg <- prune_taxa(taxa_sums(physeq.Al.neg) > 0, physeq.Al.neg)

physeq.In.pos <- prune_samples(sample_data(physeq)$Inoculation %in% c("pos"), physeq)
physeq.In.pos <- prune_taxa(taxa_sums(physeq.In.pos) > 0,physeq.In.pos)

physeq.In.neg <- prune_samples(sample_data(physeq)$Inoculation %in% c("pos"), physeq)
physeq.In.neg <- prune_taxa(taxa_sums(physeq.In.neg) > 0,physeq.In.neg)
```
###Beta

###PERMANOVA All
```{r, echo=FALSE, rows.print = 112}
permanova.forloop <- function(factor){
  require(vegan)
  require(phyloseq)
  dist <- phyloseq::distance(physeq, "bray")
  metadata <- as(sample_data(physeq@sam_data), "data.frame")
  ad <- adonis2(as.formula(paste( "dist ~", factor)), data = metadata)
  ad <- cbind2(ad[2,][3], ad[2,][5])
  return(ad)
}
physeq <- ps
permanova.forloop.pos <- possibly(permanova.forloop, otherwise = NA)
out <- map(colnames(physeq@sam_data), permanova.forloop.pos)
out.d <- do.call("rbind", out)
out.d[order(out.d$`Pr(>F)`),]


```

###PERMANOVA Plant
```{r, echo=FALSE, rows.print = 112}
permanova.forloop <- function(factor){
  require(vegan)
  require(phyloseq)
  dist <- phyloseq::distance(physeq, "bray")
  metadata <- as(sample_data(physeq@sam_data), "data.frame")
  ad <- adonis2(as.formula(paste( "dist ~", "Plant/", factor)), data = metadata)
  ad <- cbind2(ad[2,][3], ad[2,][5])
  return(ad)
}
physeq <- ps
permanova.forloop.pos <- possibly(permanova.forloop, otherwise = NA)
out <- map(colnames(physeq@sam_data), permanova.forloop.pos)
out.d <- do.call("rbind", out)
out.d[order(out.d$`Pr(>F)`),]


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
